global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "alert.rules.yml"  # 如果需要告警，取消注释并创建文件

# 抓取任务配置
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 抓取 JMeter Windows要用 host.docker.internal 这个特殊 DNS
  - job_name: 'jmeter'
    static_configs:
      - targets: ['host.docker.internal:9270']
        labels:
          instance: 'local-jmeter'
